### ISSUE TITLE
Program too awesome

### ISSUE THREAD

**Issue by gdoesntknowjava** [rocketbooster1000/SwerveVisualizer#3]
When your in ohio
Couldn't look in the gyatt
Just like Adin Ross
Your mew makes me edge
You rizz like Kai Cenat
In a skibbidi world
I wish I was sigma
You're so f*cking sigma

But I'm baby gronk
Not a rizzler
Why the hell am I mewing here?

**Comment by rocketbooster1000** [comment]
# closed: against community guidlines

no further description
